---
title: "coursework_2"
output: html_document
---

```{r}
library("readr")
```




```{r}
install.packages("bio3d", dependencies=TRUE)
```

```{r}
library(bio3d)
```


```{r}
library("readr")
df <- readr::read_csv2("../pkas.csv")
head(df)
```
```{r}
summary(df)
df[9999,]
```

There are 12,628,148 sequences!
It would be required to obtain the sequences of each, alongside their pKa values.

```{r}
colnames(df)
```

```{r}
library(dplyr)
newdf <- df %>%
  filter(idcode == c("1atp", "3p5j"))

newdf
```


```{r}
uniqueid <- unique(df$idcode)
length(uniqueid)
```

121294 total unique proteins





---------------------------------------------
Sequences
---------------------------------------------

```{r}
testset <- uniqueid[1:10]
# data I want to put into PDBe API as a test.
# argument sake, we will take 10 ids first
testset


```


```{r}
writeLines(testset)
```

I somehow want to get the testset sequences from PDB, remember to append their chain and residue number?

```{r}
first1k <- uniqueid[9001:10000]
ids <- c(first1k)
writeLines(ids,"pdb10.txt")
```


```{r}
df
```
# From here, we will be working with the dataframe that is merged:

```{r}
library("readr")
df_merged <- read_csv("../merged.csv")
head(df_merged)
```

```{r}
length(df_merged)
```
```{r}
m_uniqueid <- unique(df_merged$idcode)
length(m_uniqueid)
```

```{r}
df_merged[3000:3010,]
```

```{r}
merged_df_filtered <- df_merged %>%
  filter(if_all(everything(), ~ !is.na(.) & . != ""))

```

```{r}
mergedfiltered_uniqueid <- unique(merged_df_filtered$idcode)
length(mergedfiltered_uniqueid)
```


